### ISSUE TITLE
Custom escape levels cant be found in editor

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/BeardLib-Editor#119]
It seems you cant easily make escape/hidden type levels since the only way to  find them in the editor menus is to have it chained to a level.

Example...
My narrative has "level_1" and "level_escape" for if you fail an objective.
Im unable to load into that level in editor because I need to have it in the narratives chain but if I do that the heist shows multiple days and I dont want that.

Edit: Election day heist also is a problem here, youre unable to look at any day besides 1

**Comment by Dilbert-JonhonsonThe999th** [comment]
Couldn't you just edit it as part of the level chain and then convert it back into an escape?

**Comment by Quackertree** [comment]
@RexTheWho I solved this in Family Jewels by just editing the file by hand. - The reason it doesn't show it, is because it only shows you the table called 'escapes', which contains stuff like escape_street, escape_cafe, etc., when in theory, ANY heist could be used as an escape. There's no specific "escape=true" rule anywhere.

**Comment by Luffyyy** [comment]
Fixed
