### ISSUE TITLE
[Bug] Beardlib Editor inputs multiple keybinds at once

### ISSUE THREAD

**Issue by Whurrhurr** [Luffyyy/BeardLib-Editor#567]
**Describe the bug**
if i select a unit/element and do CTRL+F (default keybind to teleport your camera to the selected unit/element's root point) it will both teleport my camera to the root point and open the unit selection menu. the desired effect here would just be moving the camera to the root point without opening the unit selection menu.
**To Reproduce**
Steps to reproduce the behavior: select a unit/element, and then do CTRL+F. your camera will teleport to the unit/element's root point and the unit selection menu will open up.

**Comment by Luffyyy** [comment]
Make sure to update BeardLib to the latest commit and test this is a little, I added support for more keys and it not prioritizes keys that have more combinations. So `CTRL+F` would fire before `F`

**Comment by Whurrhurr** [comment]
just got around to testing it, the keybind for Spawn Unit and Spawn Element are no longer functional even if i'm not pressing CTRL. and the reason is... another keybind is also taking their spot at the same time.
![218620_20210414171600_1](https://user-images.githubusercontent.com/33162051/114796108-f04f5500-9d44-11eb-88e8-5983a92b9916.png)
i use the default keybinds as well, none of these are changed.

**Comment by Luffyyy** [comment]
The default for spawn unit is 1 for example, not F. Just change the binding of rotate unit, the current system has to stop searching for keys at the first key it finds, so this is more or less expected behavior. A possible way to to mitigate that would be to have keybinds report if they can be used at all. So if you aren't grabbing something, or spawning, it woule let another keybind use that key.
