### ISSUE TITLE
Spawning Instances with InstancePoint element breaks the Instance

### ISSUE THREAD

**Issue by sooooosh** [Luffyyy/BeardLib-Editor#581]
**Describe the bug**
When using the InstancePoint element on an Instance somehow breaks it. You can't interact with it anymore and InstanceInputEvent elements don't seem to work in it anymore as well. 

Without using InstancePoint, the Instance works perfectly fine and can receive Inputs, but that defeats the whole point of it.

**To Reproduce**
Spawn in any instance, try to interact with it.
Useing InstancePoint on said instance will make it not be interactable anymore and it can't receive inputs from InstanceInputEvent anymore.

**Comment by MiamiCenterPL** [comment]
We've spoke about it on Discord already, but I feel like I should also write it down here;
The problem is not with InstancePoint element itself, but with every instance that has variable 'MissionPlaced' set to true.
For every instance with MissionPlaced set to true entire mission script is not working at all (even stuff with "Execute on Startup").
It's like there's no mission script inside instance at all. It does apply to Custom Instances while in editor. 
However, this bug applies only when you restart heist, at first attempt it will work just fine. Soo to replicate this issue you have to place your instance, add a InputEvent (to test it) and then restart heist. After restart you can execute InputEvent manually - you'll see that it doesn't work at all.

I've tested some stuff about it; 
It does apply to Vanilla Instances aswell, however - it applies ONLY in EDITOR, while you test map normally (by buying contract in Crime.net) - they are working as expected.
